name: release

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-latest, windows-latest]

    steps:
      - name: Checkout to vrelease
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.6'

      - name: Refresh package list
        run: nimble refresh

      - name: Compile vrelease
        run: make build

      - name: Rename artifact
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            ARTIFACT="vrelease-${GITHUB_SHA}-linux"
            mv vrelease "$ARTIFACT"
          fi

          if [ "${{ matrix.os }}" = "ubuntu-24.04-arm" ]; then
            ARTIFACT="vrelease-${GITHUB_SHA}-linux-arm64"
            mv vrelease "$ARTIFACT"
          fi

          if [ "${{ matrix.os }}" = "macos-15-intel" ]; then
            ARTIFACT="vrelease-${GITHUB_SHA}-macos-x86_64"
            mv vrelease "$ARTIFACT"
          fi

          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            ARTIFACT="vrelease-${GITHUB_SHA}-macos-arm64"
            mv vrelease "$ARTIFACT"
          fi

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            ARTIFACT="vrelease-${GITHUB_SHA}-windows.exe"
            mv vrelease.exe "$ARTIFACT"
          fi

          ls -lash
          echo "ARTIFACT=$ARTIFACT" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ARTIFACT }}"
          path: "${{ env.ARTIFACT }}"
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: vrelease-${{ github.sha }}-linux
          path: linux-artifact

      - name: Download linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: vrelease-${{ github.sha }}-linux-arm64
          path: linux-arm64-artifact

      - name: Download macos x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: vrelease-${{ github.sha }}-macos-x86_64
          path: macos-x86_64-artifact

      - name: Download macos arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: vrelease-${{ github.sha }}-macos-arm64
          path: macos-arm64-artifact

      - name: Download windows artifact
        uses: actions/download-artifact@v4
        with:
          name: vrelease-${{ github.sha }}-windows.exe
          path: windows-artifact

      - name: Prepare artifacts
        run: |
          mv linux-artifact/vrelease-* vrelease-linux
          mv linux-arm64-artifact/vrelease-* vrelease-linux-arm64
          mv macos-x86_64-artifact/vrelease-* vrelease-macos-x86_64
          mv macos-arm64-artifact/vrelease-* vrelease-macos-arm64
          mv windows-artifact/vrelease-*.exe vrelease-windows.exe
          chmod +x vrelease-linux

      - name: Make release
        run: |
          ./vrelease-linux \
            -limit 50 \
            --add-checksum \
            --attach vrelease-linux \
            --attach vrelease-linux-arm64 \
            --attach vrelease-macos-x86_64 \
            --attach vrelease-macos-arm64 \
            --attach vrelease-windows.exe
        env:
          VRELEASE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
